name: Continous Integration

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    # step 1: Checkout GitHub Action
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    # step 2: Docker login
    - name: 'Docker login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER}}
        username: ${{ secrets.REGISTRY }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # step 3: Build Docker Server Image
    - name: Build Docker
      run: docker build Hotel.Server/ -t ${{ secrets.REGISTRY_LOGIN_SERVER}}/server:${{ github.sha }}

    # step 4: Push Server Image to Azure Registry
    - name: Push Docker
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER}}/server:${{ github.sha }}

    # step 5: Build Docker Client Image
    - name: Build Docker
      run: docker build Hotel.Client/ -t ${{ secrets.REGISTRY_LOGIN_SERVER}}/client:${{ github.sha }}

    # step 6: Push Client Image to Azure Registry
    - name: Push Docker
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER}}/client:${{ github.sha }}
