name: Continous Integration

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    # step 1: Checkout GitHub Action
    - name: Checkout GitHub Action
      uses: actions/checkout@development

    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER}}
        username: ${{ secrets.REGISTRY }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker Server image
      run: docker build Hotel.Server/ -t ${{ secrets.REGISTRY_LOGIN_SERVER}}/server:${{ github.sha }}

    - name: Push Docker Server image
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER}}/server:${{ github.sha }}

    - name: Build Docker Client image
      run: docker build Hotel.Client/ -t ${{ secrets.REGISTRY_LOGIN_SERVER}}/client:${{ github.sha }}

    - name: Push Docker Client image
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER}}/client:${{ github.sha }}
